### ISSUE TITLE
compilation warnings

### ISSUE THREAD

**Issue by wangyuehi** [NVIDIA-RTX/MathLib#1]
Hi,

I had a few compilation warnings during the integration of NRD 3.7.0:
there are several warnings on PS5 due to unused paramters passed to functions:

for example, 
STL.hlsl:
```
DiffuseTerm_Lambert
GeometryTermMod_Implicit
GeometryTermMod_Neumann
GeometryTermMod_SmithUncorrelated
```
have warnings:
```
// warning : unreferenced formal parameter 'linearRoughness'
// warning : unreferenced formal parameter 'NoL'
// warning : unreferenced formal parameter 'NoV'
// warning : unreferenced formal parameter 'VoH'
// warning : unreferenced formal parameter 'NoH'
```
and NRD.hlsl
```
NRD_FrontEnd_PackNormalAndRoughness
```
has 
```
// warning : unreferenced formal parameter 'materialID'
```
these warnings are spamming the log.

Thanks

**Comment by dzhdanNV** [comment]
@wangyuehi Hi! Thanks. DXC is going to add support for `[[maybe_unused]]`. Is there is something similar on PS? Or is there a way to suppress this warning on PS5 in `STL.hlsli` file?

**Comment by dzhdanNV** [comment]
These unused parameters are here by design to allow easy function plugging without a need to change the code. I would suggest suppressing such warning messages on your end.
