### ISSUE TITLE
GetQuaternion() -> SetupByQuaternion() -> GetRotationYPR() Does not yield the same rotation

### ISSUE THREAD

**Issue by oreyg** [NVIDIA-RTX/MathLib#2]
I found that calling those functions in succession does not result in the same rotation. To test this I've multiplied all intermediate rotations by a vector and compared resulting vectors between each other. My assumption is that the culpitt is "GetQuaternion()".
I've used this function to multiply quaternion by a vector:
```
PLATFORM_INLINE float3 Rotate(const float4& q1, const float3& v1)
{
    float3 q{ q1.x, q1.y, q1.z };
    float3 t = Cross(q * 2.f, v1);
    return v1 + t * q1.w + Cross(q, t);
}
```

**Comment by dzhdanNV** [comment]
Thanks! Sorry I missed this issue. I will fix.

**Comment by dzhdanNV** [comment]
@oreyg Thanks! I fixed the problem, but I haven't updated GitHub yet:
- `GetQuaternion` was wrong
- `SetupByQuaternion` produced inverted (transposed) matrix

**Comment by dzhdanNV** [comment]
Fixed \O/
