### ISSUE TITLE
GetSpecularLobeHalfAngle function potentially missing a square root term

### ISSUE THREAD

**Issue by sasamiyatu** [NVIDIA-RTX/MathLib#3]
The following function is used to compute the specular lobe half angle 
```        // Defines a cone angle, where micro-normals are distributed
        float GetSpecularLobeHalfAngle( float linearRoughness, float percentOfVolume = 0.75 )
        {
            float m = saturate( linearRoughness * linearRoughness );

            // Comparison of two methods:
            // https://www.desmos.com/calculator/4vvg1qrec7
            #if 1
                // [Lagarde 2014, "Moving Frostbite to Physically Based Rendering 3.0"]
                // https://seblagarde.files.wordpress.com/2015/07/course_notes_moving_frostbite_to_pbr_v32.pdf (page 72)
                // TODO: % of NDF volume - is it the trimming factor from VNDF sampling?
                return atan( m * percentOfVolume / ( 1.0 - percentOfVolume ) );
            #else
                return Math::DegToRad( 180.0 ) * m / ( 1.0 + m );
            #endif
        }
```
The function presented in  [Lagarde 2014, "Moving Frostbite to Physically Based Rendering 3.0"] on page 72 is $atan(\frac{E\alpha^2}{1-E})$, which is implemented here. However, the Mathematica file accompanying the paper has a square root term that is missing from the paper. This seems to be a mistake. The function presented in the Mathematica file is ${atan(\sqrt{\frac{E\alpha^2}{1-E}})}$. The Mathematica files are also available at https://seblagarde.wordpress.com/2015/07/14/siggraph-2014-moving-frostbite-to-physically-based-rendering/ (Page 3 in 4-9-3-DistanceBasedRoughnessLobeBounding.pdf).

Is the missing square root term an intentional change, or is this a mistake that has been propagated from the original paper? It seems like in the above function, *linearRoughness* might be used in place of *roughness* in an attempt to correct for the initial mistake in the formula. If so, should this function maybe be changed to use *roughness* with the correct formula including the square root term?

**Comment by dzhdanNV** [comment]
Hi! Sharp eye. Thank you!

> Is the missing square root term an intentional change, or is this a mistake that has been propagated from the original paper?

I have never looked at the Mathematica file. I just copied the code from the paper. So, if there is a mistake I just copied it. I will add the missing square root.

**Comment by dzhdanNV** [comment]
I would prefer to use the original correct formula instead of trying to "match" with "linearRoughness".

**Comment by dzhdanNV** [comment]
Fixed. Thank you very much!
